const String Preplogo = "assets/images/prepulse_circle_logo.png";
const String Splashscreenlogo = "assets/images/Prepulse_splashscreen_logo.gif";
const String Prepbanner = "assets/images/prepulse_banner.png";
const String Welcome = "assets/images/Welcome page.png";
const String Login = "assets/images/Login.png";
const String SignUp = "assets/images/SignUp.png";
const String Google = "assets/images/google_photo.png";
const String Apple = "assets/images/apple_logo.png";
const String Facebook = "assets/images/facebook_logo.png";