// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ4QYk1c8mWtUN8jwZc0XcIw2G1bWJmU8',
    appId: '1:1094036504525:web:391962eb925d3dc12cce84',
    messagingSenderId: '1094036504525',
    projectId: 'preppulse-1ea65',
    authDomain: 'preppulse-1ea65.firebaseapp.com',
    storageBucket: 'preppulse-1ea65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6-oC_b5db84YGDDVkGv-O4MlPKaqOzCY',
    appId: '1:1094036504525:android:8b78a5dd2e1344c62cce84',
    messagingSenderId: '1094036504525',
    projectId: 'preppulse-1ea65',
    storageBucket: 'preppulse-1ea65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8A7BdpFoEMRiKH9EEgsZ0zz8JpDqSfn8',
    appId: '1:1094036504525:ios:d0cfbb51ec9fd3702cce84',
    messagingSenderId: '1094036504525',
    projectId: 'preppulse-1ea65',
    storageBucket: 'preppulse-1ea65.appspot.com',
    iosBundleId: 'com.example.prepulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8A7BdpFoEMRiKH9EEgsZ0zz8JpDqSfn8',
    appId: '1:1094036504525:ios:d0cfbb51ec9fd3702cce84',
    messagingSenderId: '1094036504525',
    projectId: 'preppulse-1ea65',
    storageBucket: 'preppulse-1ea65.appspot.com',
    iosBundleId: 'com.example.prepulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ4QYk1c8mWtUN8jwZc0XcIw2G1bWJmU8',
    appId: '1:1094036504525:web:c724f54c43df475d2cce84',
    messagingSenderId: '1094036504525',
    projectId: 'preppulse-1ea65',
    authDomain: 'preppulse-1ea65.firebaseapp.com',
    storageBucket: 'preppulse-1ea65.appspot.com',
  );
}
